In [16]:
import keyword 
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [17]:
print(len(keyword.kwlist))

35


In [18]:
# rules for writing identifiers 
# 1. identifiers ca be a combiatio of letters in lowercase ( A to Z ) or an underscore( _ ).
# 2. A identifier cannot start with a digit. '99somename' is invald but 'somename99' is perfectly fine.
# 3. Keywords cannot be used as identifiers. 

In [19]:
somename99 = 10
print(somename99)

10


In [20]:
def func(): 
    '''
    This is a docstring
    '''
print(func.__doc__)


    This is a docstring
    


Advaced Python
Part - 1 

In [21]:
import time 
import numpy as np

size_of_vec =10000000

def pure_python_version():
    time_python = time.time()
    my_list1 = range(size_of_vec)
    my_list2 = range(size_of_vec)
    sum_list = [my_list1[i] + my_list2[i] for i in range(len(my_list1))]
    return time.time() - time_python

def numpy_version(): 
    time_numpy = time.time()
    my_arr1 = np.arange(size_of_vec)
    my_arr2 = np.arange(size_of_vec)
    sum_array = my_arr1 + my_arr2
    return time.time() - time_numpy

python_time = pure_python_version()
numpy_time = numpy_version()
print("Pure python version {:0.4f} " .format(python_time))
print("Numpy version : {:0.4f} : " .format(numpy_time))
print("Numpy is in this example {:0.4f} time faster  " .format(python_time/numpy_time))

Pure python version 9.7399 
Numpy version : 0.1313 : 
Numpy is in this example 74.1536 time faster  


Takeaway : Numpy is much faster than Python list ( 62 times of more )

In [22]:
import numpy as np 
# importing numpy as np , so instead of using numpy, will use 'np'

# key feature of numpy array 
# 1. can create n-dimension array in numpy array 
# 2. Allows you to have large number of arrays, datas , and will compute it really fast 

my_list = [1,2,3,4]
my_list 


[1, 2, 3, 4]

In [23]:
type(my_list)

list

In [24]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

In [25]:
type(arr)
# displayig the data type of arr - will retur numpy.ndarray

numpy.ndarray

In [29]:
my_mat = [[1,2,3] , [4,5,6] , [7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
type(mat)

numpy.ndarray

In [31]:
arr.shape
# the shape of the array  - order of the matrix ( 4 rows and 0 colums )

(4,)

In [33]:
mat.shape
# the shape of mat- order of mat - 3 x 3 
# 3 rows and 3 columns 

(3, 3)

In [35]:
arr.dtype
# dtype - gives you what type of data is stored in the list / array 
# int32 - integer with byte size of 32 

dtype('int32')

In [36]:
mat.dtype
# dtype - gives you what type of data is stored in the list / array 
# int32 - integer with byte size of 32 

dtype('int32')

In [37]:
np.arange(0,10)
# arange()   - gives you the numpy range 
# similar to range()  but faster than that 
# arange(0,10) - prints numbers from 0 to 9 - total 10 numbers 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# using stepsize in arange()
np.arange(0,10,3)
# prints the range - form 0 to 9
# with a step of 3 
# default syntax - np.arange(start , stop , step)
# if step is not specified , then the step size if 1 by default 

array([0, 3, 6, 9])

In [43]:
np.arange(0,10,1)
# same to 
# np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.zeros(4)
# fills an nparray with 4 zeros 
# the matrix will then be of the order - 1 x 4 ( 1 row and 4 columns )

array([0., 0., 0., 0.])

In [47]:
np.zeros((3,3))
# fills the nparray with 3*3 = 9 zeros 
# the order of the nparray will then be - 3 x 3 - (3 rows and 3 columns)
# the firt 4 is the column , if the rows is not specified , the by defult , it is set o
# to 1 
# the secod 4 is the number of rows 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])