In [2]:
import numpy as np
np.linspace(0,5,10)
# gives decimal points til 10th decimal

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [3]:
np.eye(3)
# gives a matrix of 3x3
# creates an identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.rand(5)
# geneerates a random number, in 5 columns 

array([8.56044635e-01, 8.35641954e-01, 7.97968947e-01, 9.79915829e-01,
       7.64721972e-04])

In [5]:
np.random.rand(2,2)
# creates a random number in 2x2 matrix form

array([[0.20129802, 0.22346866],
       [0.80343107, 0.75804576]])

In [7]:
temp = np.random.rand(9)
print(temp)
# creates a  random number
# in 9 columns 

[0.23222225 0.90067059 0.90378959 0.67288676 0.93160542 0.13567429
 0.17648771 0.52842357 0.40067181]


In [8]:
my_arr = np.arange(0,11)
my_arr
# creates an np.arange()
# form 0, to 11 ( 11 excluded )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
my_arr[1]

1

Array Slicing 

In [10]:
my_arr[1:5]

array([1, 2, 3, 4])

In [11]:
my_arr[5:1:-1]

array([5, 4, 3, 2])

In [13]:
my_arr[:-11:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
my_arr[:-12:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [15]:
# numpy arrays are mutant 
my_arr[1] = 12
my_arr

array([ 0, 12,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
my_arr[3:7] = 99
my_arr

array([ 0, 12,  2, 99, 99, 99, 99,  7,  8,  9, 10])

In [20]:
arr_2d = np.array([[0,1,2] , [3,4,5] , [6,7,8]])
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr_2d[0,1]

1

In [22]:
arr_2d[0:2 , 0:2]

array([[0, 1],
       [3, 4]])

In [23]:
arr_2d[:2 , 1:]

array([[1, 2],
       [4, 5]])

Conditional Indexing in Array 

In [26]:
arr = [1,2,3,4,5]
print(arr)
# arr>2
# gives an error

[1, 2, 3, 4, 5]


In [28]:
arr_cmd = np.arange(2,15)
arr_cmd

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr_cmd[[0,2,4]]

array([2, 4, 6])

In [32]:
arr_cmd[[False,  True, False, True,False,False,True,True,False, True, False, False, False]]
# prints all the values, which are True ( same index ) 
# index 1 - True, prints arr_cmd[1]

array([ 3,  5,  8,  9, 11])

In [33]:
arr_cmd > 2
# checks all the elements of the arr_cmd 
# if that element is greater than 2 , then stores True, else False 

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [35]:
arr_cond = np.arange(2,15)
arr_cond[arr_cmd > 8]
# PRITS ALL those elements in the arr_cond array 
# which is greater tha 8 

array([ 9, 10, 11, 12, 13, 14])

In [36]:
arr_cond > 4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

Numpy Array Operations 

1. if 2 dimension are equal , you can continue 
2. if one of the operatnd is 1, stretch it to match the largest one 
3. When one of the shapes run out of dimension ( necause it has less dimension than the other things ). Numpy will assign 1 in the compulsion process until the other shape's dimensions run out as well.

In [42]:
arr_2d = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr_2d.shape
# gives you the order of the array 

(3, 3)

In [44]:
scaler = 3 
scaler 

3

In [45]:
arr_2d + 3
# adds 3 to all the elements of the array 

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
arr_1d = np.array([10,10,10])
arr_1d.shape

(3,)

In [48]:
print(arr_1d)
print()
print()
print(arr_2d)

[10 10 10]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
arr_2d + arr_1d
# adds the elements of arr_2d and arr_1d ( adds the 1st row of arr_1d to 1st 
# row of arr_2d , then adds to the 2nd row of the arr_2d, then adds to the 3rd row 
# of the arr_2d)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [52]:
arr = np.array([[1,1,1,1]])
print(arr)
print()
print()
print(arr_2d)

[[1 1 1 1]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
# adding the 2 arrays 
# arr_2d + arr
# gives error , because , there are 3 columns in arr_2d 
# and 4 columns in arr 

In [56]:
arr = np.array([1,1,1])
arr + arr_2d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Numpy Mathematical Functions 

In [57]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[0] = 2
arr

array([ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr.min()
# prints the minimum number of the array

2

In [63]:
arr.max()
# prints the maximum number of the array 

10

In [66]:
a = [5,4,3,2,1]
# a.min()
# gives error 

# instead use the below 
min(a)
# this is because, arr is a list and not an array 
# for array - a.min()
# for list - min(a)


1

In [67]:
arr.argmin()
# gives the position of the minimum number of the array

0

In [68]:
arr.argmax()
# the position of the maximum number of the array

9

In [70]:
np.sqrt(arr)
# gives the square root of each number in the array

array([1.41421356, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [71]:
arr.min()

2

In [72]:
np.exp(arr)
# gives the e^x , value of all the numbers of the array 
# gives the exponential value

array([7.38905610e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

Exponential function is used in Activation functions of Neural functions 

Array Manipulation 

1. Change in Structure or Shape of Array 

In [73]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
#arr_2D = arr.reshape(4,2)
#arr_2D 

In [102]:
arr_2D = arr.reshape(4,4)
arr_2D

ValueError: cannot reshape array of size 15 into shape (4,4)

In [104]:
arr.transpose()
# converts rows to columns and vice versa 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Merging and Splitting Arrays 

In [111]:
arr_x = np.array([[1,2,3,4] , [5,6,7,8]])
arr_y = np.array([[21,22,23,24] , [25,26,27,28]])

In [112]:
arr_x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [113]:
arr_y

array([[21, 22, 23, 24],
       [25, 26, 27, 28]])

In [116]:
arr_2 = np.concatenate((arr_x , arr_y) , axis=1)
arr_2
# cocateates the array s

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28]])

In [117]:
print(arr_x)
print()
print(arr_y)
print()
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]

[[21 22 23 24]
 [25 26 27 28]]

[[ 1  2  3  4 21 22 23 24]
 [ 5  6  7  8 25 26 27 28]]


In [118]:
np.hsplit(arr_2 , 2)
# splits the array into 2 equal halves alog besides the columns 

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28]])]

In [119]:
np.vsplit(arr_2 , 2)
# vertically splits the array 

[array([[ 1,  2,  3,  4, 21, 22, 23, 24]]),
 array([[ 5,  6,  7,  8, 25, 26, 27, 28]])]